### ISSUE TITLE
sentiment_ninja_vader_dict.body.sql is incomplete

### ISSUE THREAD

**Issue by rimblas** [morten-egan/sentiment_ninja#1]
Hi Morten,
Looks like `sentiment_ninja_vader_dict.body.sql` doesn't have the full list of words from https://github.com/cjhutto/vaderSentiment/blob/master/vaderSentiment/vader_lexicon.txt
It stops somewhere in the m's.

I can do a pull request with the full lexicon if you don't already have it.

**Comment by morten-egan** [comment]
Sure thanks.

**Comment by morten-egan** [comment]
Spent a couple of minutes on it this afternoon. Fixed.

**Comment by rimblas** [comment]
Great, thank you
